# production:
#   adapter: postgresql
#   encoding: unicode
#   host: postgresql6.locum.ru
#   database: 
#   username: 
#   password: 

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: vkbot
  username: ns
  password: 14156

test:
  adapter: postgresql
  encoding: unicode
  host: postgresql6.locum.ru
  database: vkbot
  username: ns
  password: 14156