production:
  adapter: postgresql
  encoding: unicode
  host: postgresql7.locum.ru
  database: nerrey_vkbot41
  username: nerrey_vkbot41
  password: tSOHg2xG

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: vkbot
  username: ns
  password: 14156

test:
  adapter: postgresql
  encoding: unicode
  host: postgresql6.locum.ru
  database: vkbot
  username: ns
  password: 14156